apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: codec-csv
spec:
  imageName: ghcr.io/th2-net/th2-codec-csv
  imageVersion: 3.1.0
  type: th2-codec
  customConfig:
    default-header:
    - CsvRecordType
    - OrderQty
    - OrdType
    - SecurityIDSource
    - ClOrdID
    - OrderCapacity
    - AccountType
    - Side
    - Price
    - SecurityID
    - TransactTime
    - SecondaryClOrdID
    - OrderID
    - ExecID
    - LeavesQty
    - Text
    - ExecType
    - OrdStatus
    - CumQty
    delimiter: ","
    encoding: UTF-8
    display-name: CodecCsv1
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError
    k8sProbes: false
    hostNetwork: false
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 50m
    service:
      enabled: false
  pins:
    mq:
      subscribers:
      - name: in_codec_decode
        attributes:
        - decode_in
        - raw
        - subscribe
        linkTo:
        - box: read-csv
          pin: out_log
      - name: in_codec_general_decode
        attributes:
        - general_decoder_in
        - raw
        - subscribe
        linkTo:
        - box: rpt-data-provider
          pin: to_codec_csv
      publishers:
      - name: out_codec_decode
        attributes:
        - decode_out
        - parsed
        - publish
      - name: out_codec_general_decode
        attributes:
        - general_decoder_out
        - parsed
        - publish
  disabled: false
