apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: read-log-refdata
spec:
  image-name: ghcr.io/th2-net/th2-read-log
  image-version: 2.3.0
  type: th2-read
  custom-config:
    log-file: "/logsToRead/security_status.txt"
    regexp: "8=FIX.+10=.+\\b\\u0001"
    regexp-groups: [0]
  pins:
    - name: read_log_refdata_out
      connection-type: mq
      attributes:
        - raw
        - publish
        - store
  extended-settings:
    chart-cfg:
      ref: schema-stable
      path: custom-component
    service:
      enabled: false
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    mounting:
      - path: "/logsToRead"
        pvcName: components
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 20m
