apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: read-csv
spec:
  imageName: ghcr.io/th2-net/th2-read-csv
  imageVersion: stub
  type: th2-read
  customConfig:
    sourceDirectory: "${user.home}/demo_outputs/"
    aliases:
      demo-csv:
        nameRegexp: csv_test.csv
    common:
      staleTimeout: PT1S
      maxBatchSize: 100
      maxPublicationDelay: PT5S
      leaveLastFileOpen: false
      fixTimestamp: false
      maxBatchesPerSecond: -1
      disableFileMovementTracking: true
    pullingInterval: PT5S
    validateContent: false
    validateOnlyExtraData: false
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError
    externalBox:
      enabled: true
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 50m
    service:
      enabled: false
  pins:
    mq:
      publishers:
      - name: out_log
        attributes:
        - raw
        - publish
        - store
  prometheus:
    enabled: false
