apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: cradle-admin
spec:
  imageName: nexus.exactpro.com:18000/th2-cradle-admin-tool
  imageVersion: 1.6.1
  type: th2-conn
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -Ddatastax-java-driver.advanced.connection.init-query-timeout="5000
        milliseconds" -Ddatastax-java-driver.basic.request.timeout="10 seconds"
    resources:
      limits:
        cpu: 600m
        memory: 602Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: true
      clusterIP:
        - name: other
          containerPort: 8080
      ingress:
        urlPaths:
          - /cradle-admin/
  cradleManager:
    timeout: 30000
