apiVersion: th2.exactpro.com/v2
kind: Th2Mstore
metadata:
  name: mstore
spec:
  imageName: ghcr.io/th2-net/th2-mstore
  imageVersion: 3.5.0
  extendedSettings:
    resources:
      limits:
        memory: 500Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 20m
    service:
      enabled: false
