apiVersion: th2.exactpro.com/v1
kind: Th2CoreBox
metadata:
  name: rpt-data-viewer
spec:
  image-name: ghcr.io/th2-net/th2-rpt-viewer
  image-version: 2.0.18
  type: th2-rpt-viewer
  extended-settings:
    service:
      enabled: false
      targetPort: 80
    resources:
      limits:
        memory: 50Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 100m
#      mounitng:
#        TBD
